<? if($this->error): ?>

<?=$this->error?>
<?else:?>
<table border="1">
<tr style="color:#ccc;"><td style="width:150px; padding:10px 5px;">Заголовок</td></tr>

<?php 

foreach ($this->post as $post){
	echo '<tr><td style="padding:10px 5px;">'.$post['Title'].'</td>
	<td style="padding:10px 5px;"><a href="'.$this->url(array('controller' => 'posts','action' => 'edit-posts', 'id' => $post['Id']),NULL,true).'">Редактировать</a></td>
	<td style="padding:10px 5px;"><a href="'.$this->url(array('controller' => 'posts','action' => 'del-posts', 'id' => $post['Id']),NULL,true).'">Удалить</a></td></tr>';
}

?>

</table>

<?endif?>
<div class="error">
<?=$this->err?>
</div>
<form enctype="multipart/form-data" style="margin-top:50px;" action="<?=$this->url(array('controller' => 'posts','action' => 'add-posts'),NULL,true) ?>" method="post">
<div>Категория</div>
<select style="color:#000;" class="colortext" name="categoryid">
	<?php 
	$cat = new Obj_DBTable_PostCategories();
		if($row['CategoryId']){
			$cat_row = $cat->getPostCategories($row['CategoryId']);
		    echo '<option value="'.$cat_row['Id'].'">'.$cat_row['CategoryName'].'</option>';
		}
		$cat_row_all = $cat->getAllPostCategories();
		if($cat_row_all){
			foreach ($cat_row_all as $post_cat){
				echo '<option value="'.$post_cat['Id'].'">'.$post_cat['CategoryName'].'</option>';
			}
		}
	
	?>
</select>
<div style="margin-top:10px;">Теги:</div>
<input style="color:#000;" class="colortext" type="text" name="tags" />
<div style="margin-top:10px;">Заголовок:</div>
<input style="color:#000;" class="colortext" type="text" name="title" />
<div style="margin-top:10px;">Введение:</div>
<textarea  cols="50" rows="8" name="introtext"></textarea>
<div>Картинка:</div>
<input type="file" name="img" />
<div style="margin-top:10px;">Стаття:</div>
<textarea id="text" cols="55" rows="20" name="fulltext"></textarea>
<div><input style="color:#000; width:100px; margin-top:10px;" class="colortext" type="submit" value="Сохранить" /></div>
</form>