

<div id="socgroups">


<div id="vk_groups" style="float:left"></div>
<script type="text/javascript">
VK.Widgets.Group("vk_groups", {mode: 0, width: "470", height: "200"}, 38914744);
</script>

<div class="fb-like-box" data-href="http://www.facebook.com/MasterskaaPrazdnikov" data-width="500" data-height="220" data-show-faces="true" data-stream="false" data-header="true" style="margin-left:10px;"></div>
</div>

</div>