<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <?php echo $this->headTitle() ?>
    <?php echo $this->headMeta() ?>
    <?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/backend/css/login.css');?>
  
<?php
  
    $this->headScript()
        ->prependFile($this->baseUrl().'/backend/js/jquery/jquery-1.8.1.min.js')
  		//->appendFile($this->baseUrl().'/js/tiny_mce/tiny_mce.js')
        ;
    echo $this->headScript();
  		
?>
</head>
<body>
    <?php echo $this->layout()->content ?>
</body>
</html>
