<?php
echo $this->doctype();
$this->headTitle()->setSeparator('');
$this->headTitle('', 'PREPEND');
//$this->headMeta()->appendName('description', 'A brief description of the site.');
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headMeta()->appendHttpEquiv('Content-Language', 'ru-RU');
?>
<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  
  <link rel="icon" type="image/png" href="<?=$this->baseUrl()?>/images/icon_M_32.png" />
   <?php 
  echo $this->headTitle();
	echo $this->headMeta();
  echo $this->headLink()
  					->appendStylesheet($this->baseUrl().'/css/style.css')
  					->appendStylesheet($this->baseUrl().'/css/noty.css')
            ;
  ?>
  <?php echo $this->headLink()
  					->appendStylesheet($this->baseUrl().'/css/style.css')
  					->appendStylesheet($this->baseUrl().'/css/noty.css')
            ;
  ?>
  
  <?php 
  
    $this->headScript()
  			->prependFile($this->baseUrl().'/js/jq/jquery-1.8.2.min.js')

  			->appendFile($this->baseUrl().'/js/jq/noty/jquery.noty.js')
  			->appendFile($this->baseUrl().'/js/jq/noty/layouts/top.js')
  			->appendFile($this->baseUrl().'/js/jq/noty/layouts/inline.js')
  			->appendFile($this->baseUrl().'/js/jq/noty/layouts/center.js')
  			->appendFile($this->baseUrl().'/js/jq/noty/themes/default.js')
  			->appendFile("//vk.com/js/api/openapi.js?64")

  							;
  			$this->headScript()->captureStart();
  			?>
    var HTTP_HOST = '<?=$this->baseUrl()?>';
    <?php if (isset($this->iventorRedirect)) { ?>
    var IVENTOR_REDIRECT = '<?=$this->iventorRedirect?>';
    $(document).ready(function(){
        showLoginPopup();
    });
    <?php } ?>

    function showError(message) {
        var n = noty({
            text: message,
            type: 'error',
            dismissQueue: true,
            layout: 'top',
            theme: 'defaultTheme'
        });
        setTimeout(function(){n.close();}, 5000);
        //alert(message);
    }
    function showNotification(message) {
        var n = noty({
            text: message,
            type: 'success',
            dismissQueue: true,
            layout: 'top',
            theme: 'defaultTheme'
        });
        setTimeout(function(){n.close();}, 5000);
        //alert(message);
    }
	

    VK.init({apiId: 3024206, onlyWidgets: true});

    <?php
        $this->headScript()->captureEnd();
        echo $this->headScript();
  	?>
</head>
<body>
    <?php echo $this->facebookLike("init"); ?>
    <div id="body">
        <?php if (isset($this->banner)) { ?>
            <div class="mt_banner">
                <div class="relpos">
                    <a class="close_mt_banner" onclick="hide_banner();">закрыть</a>
                </div>
                <?php if ($this->banner->filetype == 'image') { ?>
                    <a href="<?=$this->banner->address?>" target="_blank"><img src="<?=$this->baseUrl()?>/banner/<?=$this->banner->filename?>" alt="" /></a>
                <?php } else { ?>
                    <?php
                        $dims = getimagesize(APPLICATION_PATH.'/../public/banner/'.$this->banner->filename);
                        $width = $dims[0];
                        $height = $dims[1];
                        $k = $width / 1000;
                        $height = intval($height / $k);
                        $width = 1000;
                    ?>
                    <object width="<?=$width?>" height="<?=$height?>" id="mymoviename">
                        <param name="movie" value="<?=$this->baseUrl()?>/banner/<?=$this->banner->filename?>" />
                        <param name="quality" value="high" />
                        <param name="wmode" value="transparent">
                        <param name="bgcolor" value="#ffffff" />
                        <embed src="<?=$this->baseUrl()?>/banner/<?=$this->banner->filename?>" wmode="transparent" quality="high" bgcolor="#ffffff" width="<?=$width?>" height="<?=$height?>" name="mymoviename" align="" type="application/x-shockwave-flash" pluginspage="http://www.macromedia.com/go/getflashplayer"></embed>
                    </object>
                <?php } ?>
            </div>
        <?php } ?>
        <div id="wrapper">
            <?php echo $this->render('blocks/siteheader.phtml'); ?>
	        <div id="content">
	            <?php echo $this->layout()->content ?>
                <?php echo $this->render('blocks/lastiventors.phtml'); ?>
				<?php echo $this->render('blocks/social.phtml'); ?>
	        </div><!-- #content-->
        </div><!-- #wrapper -->
    <?php  echo $this->render('blocks/footer.phtml'); ?>
    </div>
</body>
</html>