<?php
    $this->headScript()->appendFile($this->baseUrl().'/js/jq/jquery.autocomplete.js');
    $this->headScript()->appendFile($this->baseUrl().'/js/jq/jquery.maskedinput-1.3.min.js');
    $this->headScript()->appendFile($this->baseUrl().'/js/popup.js');
    $this->headScript()->appendFile($this->baseUrl().'/js/auth.js');
    $this->headScript()->appendFile($this->baseUrl().'/js/info.js');
    $this->headLink()->appendStylesheet($this->baseUrl().'/css/popup.css');
    $this->headLink()->appendStylesheet($this->baseUrl().'/css/faq2.css');
    $this->headLink()->appendStylesheet($this->baseUrl().'/css/faq3.css');
    $this->headLink()->appendStylesheet($this->baseUrl().'/css/jquery.autocomplete.css');
?>
<script type="text/javascript">
    $(document).ready(function(){
        //showRegisterEventorPopup();
    });
</script>
<h2 class="for_eventor_title"><span>"Мастерская праздников"</span> - станет вашим основным инструментом для поиска целевых клиентов!</h2>
<p class="for_eventor_desc"><span style="color:#a00608;"><i><b>“Мастерская праздников”</b></i></span> - это удобный ресурс, который будет полезен всем участникам, причастным к процессу создания мероприятий, корпоративов, праздников и всем тем, кто действительно любит дарить людям радость!</p>
</br>
<h3 class="for_eventor_title_small">Преимущества сервиса:</h3>
<ul class="service_advantages">
    <li><span>1</span>Клиенты могут найти вас через комплексный поиск или каталог.</li>
    <li><span>2</span>Проверенные контактные данные клиента. Вы сразу же можете позвонить или написать e-mail.</li>
    <li><span>3</span>СМС нотификация с прямым номером клиента для мгновенных звонков.</li>
    <li><span>4</span>Личный аккаунт с детальной информацией, услугами, портфолио и видео. </li>
    <li><span>5</span>Skype виджет, поможет клиентам еще быстрее связываться с вами. </li>
    <li><span>6</span>Календарь, где вы будете отмечать дни, когда вы заняты. Сэкономьте время себе и клиенту.</li>
    <li><span>7</span>Клиенты мгновенно высылают вам запрос через кнопку «Перезвоните мне».</li>
    <li><span>8</span>Возможность клиенту добавлять вас в Избранное, чтобы в будущем продолжить с вами работу.</li>
    <li><span>9</span>...и много других…</li>
</ul>
</br>
<h3 class="for_eventor_title_small">Тарифы и возможности.</h3>
<p class="for_eventor_desc">На сервисе <span style="color:#a00608;"><i><b>“Мастерская праздников”</b></i></span> существует два аккаунта <b><i>“Премиум”</b></i> и <b><i>“Бесплатный”</b></i>.</p>
<div align="center">
<div class="tip"><div class="tipcontent"></div></div>
<table width="800" cellspacing="0" cellpadding="0">
<tr><th class="col1"></th><th class="col2"></th><th class="col3"></th></tr>
<tr><td class="col1_dark">Персональная страница<div class="info" id="inf1"/></td><td class="col2_dark"><div class="check"/></td><td class="col3_dark"><div class="check not"/></td></tr>
<tr><td class="col1">Отзывы на странице<div class="info" id="inf2"/></td><td class="col2"><div class="check"/></td><td class="col3"><div class="check not"/></td></tr>
<tr><td class="col1_dark">Фотографий в профиле<div class="info"/></td><td class="col2_dark">30</td><td class="col3_dark">10</td></tr>
<tr><td class="col1">Видео в профиле<div class="info"/></td><td class="col2">3</td><td class="col3">0</td></tr>
<tr><td class="col1_dark">Размещение в каталоге<div class="info"/></td><td class="col2_dark">большое, вверху</td><td class="col3_dark">маленькое, внизу</td></tr>
<tr><td class="col1">Участие в комплексном поиске<div class="info"/></td><td class="col2"><div class="check"/></td><td class="col3"><div class="check_not"/></td></tr>
<tr><td class="col1_dark">Функция «Перезвонить мне»<div class="info"/></td><td class="col2_dark"><div class="check"/></td><td class="col3_dark"><div class="check_not"/></td></tr>
<tr><td class="col1">СМС нотификация с номером клиента<div class="info"/></td><td class="col2"><div class="check"/></td><td class="col3"><div class="check_not"/></td></tr>
<tr><td class="col1_dark">Возможность быть в Избранном клиента<div class="info"/></td><td class="col2_dark"><div class="check"/></td><td class="col3_dark"><div class="check_not"/></td></tr>
<tr><td class="col1">Skype виджет для быстрой связи<div class="info"/></td><td class="col2"><div class="check"/></td><td class="col3"><div class="check_not"/></td></tr>
<tr><td class="col1_dark">Календарь занятости<div class="info"/></td><td class="col2_dark"><div class="check"/></td><td class="col3_dark"><div class="check_not"/></td></tr>
<tr><td class="col1">Публикация в соц. сетях<div class="info"/></td><td class="col2"><div class="check"/></td><td class="col3"><div class="check_not"/></td></tr>
<tr><td class="col1_foot"><span style="text-decoration: line-through;">Стоимость*:</span><span style="color:#a00608;text-transform: uppercase; fomt-size:45px; margin-left:10px;">АКЦИЯ!!!</span></td><td class="col2_foot">Украина: <strong>100</strong> грн/мес<br>Россия: <strong>500</strong> руб/мес</td><td class="col3_foot"></td></tr>
<tr><td></td><td class="subbot"></td><td></td></tr>
<tr><td colspan="3" class="bottom">*При покупке “Премиум” аккаунта на  3, 6, 12 месяцев действуют хорошие скидки!!!</td></tr>
</table>
</br></br></br>
</div>
<div align="center" class="prem2">
<table width="890" cellspacing="0" cellpadding="0">
<tr style="text-align:center; font-family: 'Trebuchet MS'; font-size:24px;"><td>
Всем зарегистрировавшимся  <span style="font-size:27px; color:#ad0000;">«Мастерская Праздников»</span></br> 
дает <span style="font-size:50px;">180</span> дней <img src="http://masterholiday.net/images/premium.png" style="margin-bottom:-12px;" /> аккаунта <span style="font-size:35px;">бесплатно</span>.<br/>
Для того что бы вы смогли попробовать все возможности сервиса.
</td></tr>
</table>
</div>
</br></br></br>
<div>
    <a href="#" onclick="showRegisterEventorPopup(); return false;" class="joinnew">Зарегистрироваться</a>
</div>